name: My Monthly Job

on:
  schedule:
    # Runs at 00:00 UTC on the first day of every month
    - cron: '0 0 * * *'

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

        # Compile TypeScript if needed
      - name: Compile TypeScript
        run: npx tsc

      - name: Run my script
        run: npm run server/utils/scrape-seo.ts
